config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :tasks do
      member do
        patch :task_completed
        patch :priority_up
        patch :priority_down
      end
    end
  end
  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :title, presence: true, uniqueness: { scope: :user_id }

  default_scope -> { order('created_at DESC') }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates :content, presence: true, uniqueness: { scope: :project_id }

  default_scope -> { order('priority ASC') }

  def deadline_formatted
    data = self.deadline.to_s
    data[0...10]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :recoverable, :rememberable, :trackable,:confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable, :rememberable

  has_many :projects, dependent: :destroy
  has_many :tasks, :through => :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

before_filter :find_project,  only: [:show, :edit, :update, :destroy]

  def new
    @project = Project.new
  end

  def index
    @projects = current_user.projects.all
  end

  def create
    @project = current_user.projects.create(project_params)
    respond_to do |format|
      if @project.errors.blank?
        flash[:success] = "Project created!"
        format.html { redirect_to root_path }
        format.js
      else
        flash.now[:danger] = "Incorrect input"
        format.html { redirect_to root_path }
      end
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash[:success] = "Project updated!"
      respond_to do |format|
        format.html {redirect_to root_path}
        format.js
      end
    else
      flash.now[:danger] = "Incorrect input"
      redirect_to root_path
    end
  end

  def destroy
    @project.destroy
    flash[:info] = "Project and all tasks to this project were deleted."
    respond_to do |format|
        format.html {redirect_to root_path}
        format.js
    end
  end


private

  def find_project
    @project = current_user.projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

before_filter :find_project
before_filter :find_task,  except: [:create]

  def index
    @tasks = @project.tasks.all
  end

  def create
    @task = @project.tasks.create task_params
    if @task.errors.any?
      flash[:danger] = "Something is wrong. Take a look at your input"
      render root_path
    else
      lowest_priority = @project.tasks.pluck(:priority).max
      @task.increment!(:priority, (lowest_priority+1))
      flash[:success] = "Task created!"
      end
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def priority_up
    priority = @task.priority
    if priority > 1
      @upper_task = @project.tasks.find_by priority: (priority-1)
      @upper_task.increment!(:priority)
      @task.decrement!(:priority)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      redirect_to root_path
    end
  end

  def priority_down
    priority = @task.priority
    lowest_priority = @project.tasks.pluck(:priority).max
    if priority < lowest_priority
      @lower_task = @project.tasks.find_by priority: (priority+1)
      @lower_task.decrement!(:priority)
      @task.increment!(:priority)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      render root_path
    end
  end

  def task_completed
    @task.toggle!(:completed)
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def edit
  end

  def update
    @task.update_attributes! task_params
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  private

  def find_task
    @task = current_user.tasks.find(params[:id])
  end

  def find_project
    @project = current_user.projects.find(params[:project_id])
  end

  def task_params
    params.require(:task).permit(:content, :deadline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_flash.html.erb
<div class="flash">
  <div class="col-md-11 col-md-offset-1">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <a href="http://rubygarage.org/">© Ruby Garage</a>
</footer>

app/views/layouts/_header.html.erb
<div class="row user">
  <div class="col-md-12">
    <% if user_signed_in? %>
    <%= current_user.email %>
    <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
    <%else%>
    <%= link_to 'Sign in', new_user_session_path %> or <%= link_to 'Sign up', new_user_registration_path %>
    <% end %>
  </div>
</div>

<header>
  <h1>Sample todo lists</h1>
  <h4>From ruby garage</h4>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(project, remote: true, validate: true, html: {class: "form-inline"}) do |f| %>
  <div class="row">
  <div class="col-md-2 col-md-offset-1 edit-project">
    <i class="fa fa-calendar fa-2x"></i>
  </div>
  <div class="col-md-7 edit-project">
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="col-md-2 edit-project" >
    <%= f.submit "Edit", class: "btn btn-default" %>
  </div>
  </div>
<% end %>

app/views/projects/_new.html.erb
<%= form_for(@project, html: {class: "form-inline"}, validate: true, remote: true) do |f| %>
    <div class="row" >
        <div class="col-md-8 offset-col-md-2">
      <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="col-md-2">
        <%= f.submit "Create project", class: "btn btn-info" %>
      </div>
    </div>
<% end %>

app/views/projects/_project.html.erb
<div class="project" id="project_<%= project.id %>">
      <%= render partial: "project_header", locals: {project: project} %>
          <%= form_for ([project, project.tasks.build]), validate: true, remote: true, html: {class: "form-inline"} do |f| %>
          <div class="row new-task">
          <div class="col-md-2 col-md-offset-1">
            <%= f.text_field :deadline, class: "task_deadline", placeholder: "YYYY-MM-DD" %>
          </div>
          <div class="col-md-7 new-task-input">
            <%= f.text_field :content, class: "form-control", placeholder: "Start typing here to create a task..." %>
          </div>
        <div class="col-md-2">
            <%= f.submit "Add task", class: "btn task" %>
          <% end %>
        </div>
      </div>
        <% project.tasks.each do |task| %>
            <%= render partial: "tasks/task", locals: {project: project, task: task} %>
        <% end %>
    </div>

app/views/projects/_project_header.html.erb
      <div class="row project-header" id="project_row_<%= project.id %>">
        <div class="col-md-2 col-md-offset-1">
          <i class="fa fa-calendar fa-2x"></i>
        </div>
        <div class="col-md-7 project-title"><%= project.title %></div>
        <div class="col-md-2 text-center">
          <%= link_to edit_project_path(project), remote: true do %>
            <i class="fa fa-pencil"></i>
          <% end %>
          <%= link_to project, method: :delete, data: { confirm: 'Are you sure?' }, remote: true  do%>
            <i class="fa fa-trash"></i>
          <% end %>
        </div>
      </div>

app/views/projects/create.js.erb
$('#new_project').remove();
$('#new_project_link').show();
$('.flash').after('<%= j render(partial: "projects/project", locals: {project: @project}) %>');

app/views/projects/destroy.js.erb
$('div#project_<%= @project.id %>').remove();

app/views/projects/edit.js.erb
$('#project_row_<%= @project.id %>').hide().after('<%= j render("form", project: @project) %>');
$('#edit_project_<%= @project.id %>').enableClientSideValidations();
$('#project_row_<%= @project.id %>').remove();

app/views/projects/index.html.erb
  <% @projects.each do |project| %>
    <%= render partial: "project", locals: {project: project} %>
    <% end %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= link_to new_project_path, id: "new_project_link", name: "new_project_link", remote: true, class: "btn project" do %>
        <i class="fa fa-plus" ></i> Add TODO list
      <% end %>
    </div>
  </div>

app/views/projects/new.html.erb
<div id="new_project"><%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/projects/new.js.erb
$('#new_project_link').hide().before('<%= j render("new") %>');
$('#new_project').enableClientSideValidations();

app/views/projects/update.js.erb
$('#edit_project_<%= @project.id %>').after('<%= j render("project_header", project: @project) %>');
$('#edit_project_<%= @project.id %>').remove();

app/views/tasks/_form.html.erb
<%= form_for([@project, @task ], validate: true, remote: true) do |f| %>
<div class="row edit-task">
  <div class="col-md-2 col-md-offset-1">
    <%= f.text_field :deadline, class: "task_deadline", placeholder: "YY-MM-DD" %>
  </div>
  <div class="col-md-7 new-task-input">
    <%= f.text_field :content, class: "form-control" %>
  </div>
  <div class="col-md-2">
      <%= f.submit "Edit task", class: "btn task" %>
  </div>
  </div>
<% end %>

app/views/tasks/_task.html.erb
      <div id="task_row_<%= task.id %>">
        <% if task.id %>
            <div class="row" >
          <div class="col-md-2 col-md-offset-1">
            <%= link_to task_completed_project_task_path(project, task.id), remote:true, method: :patch do %>
              <% if task.completed == false then %>
                <i class="fa fa-square-o" id="checkbox"></i>
              <% else %>
                <i class="fa fa-check-square-o" id="checkbox"></i>
              <% end %>
            <% end %>
            <span class="deadline-formatted" ><%= task.deadline_formatted %></span>
          </div>
          <div class="col-md-7">
              <%= task.content %>
          </div>
          <div class="col-md-2 text-center">
              <%= link_to priority_up_project_task_path(project, task.id), method: :patch, remote: true do %>
                <i class="fa fa-arrow-up"></i>
              <% end %>
              <%= link_to priority_down_project_task_path(project, task.id), method: :patch, remote: true do %>
                <i class="fa fa-arrow-down"></i>
              <% end %>
              <%= link_to edit_project_task_path(project, task), remote: true do %>
                <i class="fa fa-pencil"></i>
              <% end %>
              <%= link_to url_for([project, task]), method: :delete, remote: true, data: { confirm: 'Are you sure?' } do %>
                <i class="fa fa-trash"></i>
            <% end %>
          </div>
      </div>
        <% end %>
      </div>

app/views/tasks/_update.html.erb
<div class="col-md-4">
  <i><%= task.content %></i>
</div>
<div class="col-md-2">
  <%= link_to edit_project_task_path(project, task), remote: true do %>
    <i class="fa fa-pencil"></i>
  <% end %>
  |<%= link_to url_for([project, task]), method: :delete, remote: true, data: { confirm: 'Are you sure?' } do %>
    <i class="fa fa-trash"></i>
  <% end %>
</div>

app/views/tasks/create.js.erb
$('#project_<%= @project.id %> #task_row_').before('<%= j render(partial: "tasks/task", locals: {project: @project, task: @task}) %>');
$('#project_<%= @project.id %> #new_task')[0].reset();

app/views/tasks/destroy.js.erb
$('#task_row_<%= @task.id %>').remove();

app/views/tasks/edit.js.erb
$('#task_row_<%= @task.id %>').after('<%= j render ("tasks/form") %>');
$('#edit_task_<%= @task.id %>').enableClientSideValidations();
$('#task_row_<%= @task.id %>').remove();

app/views/tasks/priority_down.js.erb
$('#task_row_<%= @task.id %>').remove();
$('#task_row_<%= @lower_task.id %>').after('<%= j render(partial: "tasks/task", locals: {project: @project, task: @task}) %>');

app/views/tasks/priority_up.js.erb
$('#task_row_<%= @task.id %>').remove();
$('#task_row_<%= @upper_task.id %>').before('<%= j render(partial: "tasks/task", locals: {project: @project, task: @task}) %>');

app/views/tasks/task_completed.js.erb
  $("#task_row_<%= @task.id %> i#checkbox").each(function(){
      if($(this).hasClass('fa fa-square-o')){
          $(this).removeClass('fa fa-square-o').addClass('fa fa-check-square-o');}
      else {
          $(this).removeClass('fa fa-check-square-o').addClass('fa fa-square-o');}
          });

app/views/tasks/update.js.erb
$('#edit_task_<%= @task.id %>').after('<%= j render(partial: "tasks/task", locals: {project: @project, task: @task}) %>');
$('#edit_task_<%= @task.id %>').remove();

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>